steps:  
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-west1-docker.pkg.dev/${PROJECT_ID}/chichivio/web:latest', '.']

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-west1-docker.pkg.dev/${PROJECT_ID}/chichivio/web:latest']

  # Step 3: Deploy the Docker image to Cloud Run, max 1 instance
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'chichivio', '--image', 'us-west1-docker.pkg.dev/${PROJECT_ID}/chichivio/web:latest', '--platform', 'managed', '--region', 'us-west1', '--allow-unauthenticated', '--max-instances', '1', '--memory', '128Mi', '--cpu', '1', --port, '5000', '--min-instances', '1']

  # # Step 4: Delete the old revision
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: ['run', 'revisions', 'delete', 'chichivio', '--platform', 'managed', '--region', 'us-west1', '--revision', '${REVISION_ID}']
  #   # Only run this step if the previous step succeeded
  #   id: 'delete-previous-revision'
  #   waitFor: ['Step #3']
  #   # Only run this step if there is a previous revision to delete
  #   condition: 'if substitutions.REVISION_ID != ""'