steps:  
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-west1-docker.pkg.dev/${PROJECT_ID}/chichivio/web:latest', '.']

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-west1-docker.pkg.dev/${PROJECT_ID}/chichivio/web:latest']

  # Step 3: Deploy the Docker image to Cloud Run, max 1 instance
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'chichivio', '--image', 'us-west1-docker.pkg.dev/${PROJECT_ID}/chichivio/web:latest', '--platform', 'managed', '--region', 'us-west1', '--allow-unauthenticated', '--max-instances', '1', '--memory', '128Mi', '--cpu', '1', --port, '5000', '--min-instances', '1']

  # Step 4: Trigger cloud function when cloud run is deployed
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'call', 'autu-cf-purge', '--data', '{"url": "https://us-west1-project-0-369106.cloudfunctions.net/autu-cf-purge"}','--region', 'us-west1']


