"""Change content column to Text

Revision ID: 8adb5914bbae
Revises: 
Create Date: 2024-10-06 08:23:49.310381

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8adb5914bbae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.VARCHAR(length=140),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=140),
               existing_nullable=False)

    # ### end Alembic commands ###
