"""nightmarkets data insert

Revision ID: fb11b154696c
Revises: 8adb5914bbae
Create Date: 2024-12-13 21:14:37.310147

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb11b154696c'
down_revision = '8adb5914bbae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_print', schema=None) as batch_op:
        batch_op.drop_column('food_type')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_print', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('food_type', mysql.VARCHAR(length=80), nullable=False))

    # ### end Alembic commands ###
