# .github/workflows/deploy.yml
name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    # steps:
    # - name: Checkout code
    #   uses: actions/checkout@v2

    # - name: Set up SSH
    #   uses: webfactory/ssh-agent@v0.5.3
    #   with:
    #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # - name: Deploy to EC2
    #   run: |
    #     ssh -o StrictHostKeyChecking=no ec2-user@your-ec2-instance-ip << 'EOF'
    #       cd /path/to/your/repository
    #       git pull origin main
    #       docker-compose down
    #       docker-compose build
    #       docker-compose up -d
    #     EOF
